#!/bin/sh

# Adjust DocumentRoot for Contao 4
if [ -f /var/www/composer.json ] && `grep -E -q 'contao/contao.*\^4\.' /var/www/composer.json`; then
  echo Contao 4 detected. Change DocumentRoot to /var/www/web
  sed  -i 's~^DocumentRoot .*~DocumentRoot "/var/www/web"~' /etc/httpd/conf/httpd.conf
fi

# run setup script
if [ -x /etc/services.d/httpd/setup ] ; then
  /etc/services.d/httpd/setup || exit $?
fi


exec /usr/sbin/httpd -D FOREGROUND
