#!/bin/bash
set -e

# Adjust UserID for apache to match permission from volume mount
if [ -n "$RUN_UID" ] ; then
  echo Set apache UID to $RUN_UID
  [[ $(id -u apache) != "$RUN_UID" ]] && usermod -u $RUN_UID apache
fi

# Adjust timezone
if [ -n "$TIMEZONE" ]; then
  echo Set TIMEZONE to $TIMEZONE
  if [ ! -e /usr/share/zoneinfo/$TIMEZONE ]; then
    >&2 echo ERROR: Could not set timezone. File /usr/share/zoneinfo/$TIMEZONE does not exist.
    exit 1
  fi
  ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
else
  echo Hint: Set your timezone using TIMEZONE env var.
fi

# PHP configuration
/conf-php

# Start Apache
exec /run-httpd
