#!/bin/bash

# kill old FPM
pkill -TERM php-form || true

if [ "$TIMEZONE" != "" ] && [ -e /etc/php.ini ] ; then
  # we use ~ as rgxp delimiter to not collide with TIMEZONEs /
  sed -r -i "s~^;?date\.timezone =.*~date.timezone = \"${TIMEZONE}\"~g" /etc/php.ini
fi

# We run php-fpm with apache user
# recreate directory to workaround wired permission bug
rm -rf /var/lib/php
mkdir -p /var/lib/php/fpm/wsdlcache
mkdir -p /var/lib/php/fpm/opcache
mkdir -p /var/lib/php/fpm/session
chown -R apache:apache /var/lib/php

# Enable xdebug
if [ "$XDEBUG" != "" ] &&  [ "$XDEBUG" != "false" ]; then
  echo Enabling xdebug
  sed -r -i "s~^;?zend_extension=xdebug\.so~zend_extension=xdebug.so~g" /etc/php.d/15-xdebug.ini
fi

# Parse $PHP_VALUE / $PHP_ADMIN_VALUE settings
parsePhpValue() {
  local k
  local v
  local t
  for t in ${!1//,/ } ; do
    k=$(echo $t | cut -d = -f 1)
    v=$(echo $t | cut -d = -f 2)
    echo "${1,,}[$k] = $v" >> /etc/php-fpm.d/www.conf
  done
}
parsePhpValue PHP_VALUE
parsePhpValue PHP_ADMIN_VALUE


exec /usr/sbin/php-fpm -D
