#!/bin/sh

# Kill old pidfile, apache is grumpy here
[ -e /var/run/httpd/httpd.pid ] && rm /var/run/httpd/httpd.pid

# Fix permissions cause apache could have another UID
chown -R apache /usr/share/httpd
rm -rf /run/httpd
mkdir -p /run/httpd
chown -R apache:root /run/httpd
chmod 775 /run/httpd

# Adjust DocumentRoot for Contao 4
if [ -f /var/www/composer.json ] && `grep -E -q 'contao/(contao|manager).*"?4\.' /var/www/composer.json`; then
  echo Contao 4 detected. Change DocumentRoot to /var/www/web
  sed  -i 's~^DocumentRoot .*~DocumentRoot "/var/www/web"~' /etc/httpd/conf/httpd.conf
fi

exec /usr/sbin/httpd -D FOREGROUND
