#!/bin/bash

if [ "$TIMEZONE" != "" ] && [ -e /etc/php.ini ] ; then
  # we use ~ as rgxp delimiter to not collide with TIMEZONEs /
  sed -r -i "s~^;?date\.timezone =.*~date.timezone = \"${TIMEZONE}\"~g" /etc/php.ini
fi

# We run php-fpm with apache user
chgrp apache /var/lib/php/* -R

# Enable xdebug
if [ "$XDEBUG" != "" ] &&  [ "$XDEBUG" != "false" ]; then
  echo Enabling xdebug
  sed -r -i "s~^;?zend_extension=xdebug\.so~zend_extension=xdebug.so~g" /etc/php.d/15-xdebug.ini
fi

# Parse $PHP_VALUE / $PHP_ADMIN_VALUE settings
parsePhpValue() {
  local k
  local v
  local t
  for t in ${!1//,/ } ; do
    k=$(echo $t | cut -d = -f 1)
    v=$(echo $t | cut -d = -f 2)
    echo "${1,,}[$k] = $v" >> /etc/php-fpm.d/www.conf
  done
}
parsePhpValue PHP_VALUE
parsePhpValue PHP_ADMIN_VALUE


if [ -x /etc/services.d/php-fpm/setup ]; then
  /etc/services.d/php-fpm/setup || exit $?
fi

exec /usr/sbin/php-fpm -F
